title: Danil Gorbunov # your name (or website title) here
logo: "/images/photo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  My previous job was in sales. But as sales increased, more time had to be spent on the little things. Sales automation got me into programming. At the moment I'm trying myself in mobile development. There is a desire to quickly go through the basics and participate in interesting business or gaming projects.
  <br><br>
  Trainy/Junior Flutter Developer Personal preference: Mobile Dev - Figma/Flutter
  HTML,CSS,Javascript,React,Git,Figma, Flutter(Dart in studying process)
  english: intermediate, russian: native, ukrainian: advanced
 
  <a href="https://www.linkedin.com/in/danilgorbunov">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
